stages:
  - build
  - deploy

variables:
  SSH_USER: ubuntu

build:
  stage: build
  image: node:18
  script:
    - npm install
    - npm run build   # this creates dist/
  artifacts:
    name: "$CI_COMMIT_REF_NAME-dist"
    paths:
      - dist/         # <-- use dist instead of build
    expire_in: 1 hour

deploy:
  stage: deploy
  image: alpine:latest
  dependencies:
    - build
  before_script:
    - apk add --no-cache openssh rsync
    - mkdir -p ~/.ssh
    - echo "$EC2_SSH_KEY" | tr -d '\r' > ~/.ssh/id_rsa
    - chmod 600 ~/.ssh/id_rsa
    - ssh-keyscan -H $SSH_HOST_DEV >> ~/.ssh/known_hosts

  script:
    - echo "Deploying to Dev server..."

    # Copy files
    - rsync -avz --delete ./ $SSH_USER@$SSH_HOST_DEV:$APP_DIR_DEV

    # Restart PM2
    - ssh $SSH_USER@$SSH_HOST_DEV "cd $APP_DIR_DEV && pm2 restart ggplastic-dev"

  only:
    - main